services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - .wireguard/config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
    network_mode: "host"

  pihole:
    image: pihole/pihole:2025.06.2
    container_name: pihole
    environment:
      - TZ=Europe/Berlin
      - FTLCONF_webserver_api_password=homelab
      # Config file in pihole is /etc/pihole/pihole.toml
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      - FTLCONF_dns_listeningMode=ALL
      #https://docs.pi-hole.net/docker/configuration/?h=ftlconf_dns_dnssec#configuring-ftl-via-the-environment
      - FTLCONF_dns_upstreams=9.9.9.9;149.112.112.112
      # https://docs.pi-hole.net/docker/upgrading/v5-v6/?h=dhcp_active#dhcp-variables
      - FTLCONF_dhcp_active=true
      - FTLCONF_dhcp_start=192.168.50.100
      - FTLCONF_dhcp_end=192.168.50.200
      - FTLCONF_dhcp_router=192.168.50.1
      - FTLCONF_dhcp_leaseTime=24h
    volumes:
      - .pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: "host"
